### ISSUE TITLE
how did you make the link rel?

### ISSUE THREAD

**Issue by RedMAngo22** [VutonDesign/bronze#2]

**Comment by VutonDesign** [comment]
Using jsdelivr.com. 

I recommend you read this issue as I noticed you use the old link - #1

**Comment by RedMAngo22** [comment]
okay thanks.

**Comment by RedMAngo22** [comment]
Can you help here?

**Comment by VutonDesign** [comment]
@RedMAngo22 Okay, What do you need help with?

**Comment by RedMAngo22** [comment]
I Made a css theme, i want to make the min,css and link rel.

**Comment by VutonDesign** [comment]
- To make a min.css file, use this site and it'll minify your file - https://cssminifier.com/
- To make a CDN link (link rel), Replace this with your info. You'll need to make a release on the repo - https://cdn.jsdelivr.net/gh/YOUR-USERNAME/YOUR-REPO@YOUR-REPO-VERSION/YOUR-CSS-FILE-NAME

**Comment by MartinKolarik** [comment]
@VutonDesign you can also skip the first step and let jsDelivr minify the file for you (just add `.min` to the filename)

**Comment by VutonDesign** [comment]
@MartinKolarik I didn't know that, Thanks 😄

**Comment by RedMAngo22** [comment]
:)

**Comment by VutonDesign** [comment]
@MartinKolarik Just noticed you actually develop jsDelivr 😆😆

**Comment by MartinKolarik** [comment]
@VutonDesign yep 😄
